### ISSUE TITLE
Outdated dependencies (`protobuf`)

### ISSUE THREAD

**Issue by ollema-zenseact** [parallel-domain/pd-sdk#306]
Hello PD team!

Recently we have run into some issues where the dependency ranges used in this project has proven to be a bit outdated. This has been problematic since we are unable to use this package in tandem with other key dependencies.

I wonder if it would be possible for you to go over this SDK and try and update the dependcies so that they use more modern versions?

The current culprit is the `protobuf` package where you have specified `protobuf>=3.20.1,<4.0.0` and where other packages require at least `>4.0.0` and the latest version is `5.28.0`.

In addition to `protobuf` I foresee problems with for example `numpy` since Numpy 2.0 has been released and I think a lot of other packages will migrate over and you have specified `numpy>=1.19,<2.0`. So if possible, it would be great with a more general overhaul of to update the listed dependencies.

We tried to update `protobuf` ourselves to make a PR to solve this but we encountered some issues with the `update_protos.sh` so we figured it was better to open an issue here.

Thanks,

Olle

**Comment by pd-bryce** [comment]
Hey @ollema-zenseact! Thanks for your patience here with this one.

The next version of the SDK (targeting 4.8) will include a `protobuf` version update to v4.25.2.

We've consolidated our protobuf code generation into a single location on our end, so the process here should be smoother for future upgrades.

We have a follow-on to take a look at other outdated dependencies. Our `numpy` dependency is one we're watching closely. We have some dependencies (e.g. `rerun-sdk`) that still depend on `numpy<2.0` in their latest releases.

We're consolidating feedback over to our Discourse channel as well. Reach out if you're not plugged into that yet.

Thanks!

**Comment by ollema-zenseact** [comment]
> Hey @ollema-zenseact! Thanks for your patience here with this one.
> 
> The next version of the SDK (targeting 4.8) will include a `protobuf` version update to v4.25.2.
> 
> We've consolidated our protobuf code generation into a single location on our end, so the process here should be smoother for future upgrades.
> 
> We have a follow-on to take a look at other outdated dependencies. Our `numpy` dependency is one we're watching closely. We have some dependencies (e.g. `rerun-sdk`) that still depend on `numpy<2.0` in their latest releases.
> 
> We're consolidating feedback over to our Discourse channel as well. Reach out if you're not plugged into that yet.
> 
> Thanks!

Hello!

Thanks @pd-bryce.

I am not part of the Discourse channel. Will ask around and see if I can get access.

Are you saying that the next SDK version will target `v4.8.0`? Given that the last release here on GitHub is `v2.7.0` - is there a another distribution channel that we have missed perhaps?
